### ISSUE TITLE
windows path replacement error

### ISSUE THREAD

**Issue by rwson** [joonhocho/tscpaths#1]
on the Windows operating system, path alias will be compiled to backslash, but it is good on the Mac.
below is my screenshots

- windows:
![windows](https://user-images.githubusercontent.com/9476421/46799014-339c6780-cd86-11e8-9170-15e822017a22.jpg)

- Mac:
![mac](https://user-images.githubusercontent.com/9476421/46798984-1d8ea700-cd86-11e8-9ca6-15e5635d8ea0.jpg)

and my useage is：
`
rimraf dist && tsc --project tsconfig.json && tscpaths -p tsconfig.json -s ./src -o ./dist
`

**Comment by rwson** [comment]
upload image error, follow is my screenshoot on windows
![windows](https://user-images.githubusercontent.com/9476421/46799122-7f4f1100-cd86-11e8-9117-f334739a12e5.png)

**Comment by joonhocho** [comment]
@rwson Just published a fix for it. Thank you!
